<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Detil_inventori extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        $this->load->model('Detil_inventori_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $detil_inventori = $this->Detil_inventori_model->get_all();

        $data = array(
            'detil_inventori_data' => $detil_inventori
        );

        $this->template->load('template','detil_inventori_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Detil_inventori_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_detil_inventori' => $row->id_detil_inventori,
		'id_inventori' => $row->id_inventori,
		'id_kamar' => $row->id_kamar,
	    );
            $this->template->load('template','detil_inventori_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('detil_inventori'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('detil_inventori/create_action'),
	    'id_detil_inventori' => set_value('id_detil_inventori'),
	    'id_inventori' => set_value('id_inventori'),
	    'id_kamar' => set_value('id_kamar'),
	);
        $this->template->load('template','detil_inventori_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'id_detil_inventori' => $this->input->post('id_detil_inventori',TRUE),
		'id_inventori' => $this->input->post('id_inventori',TRUE),
		'id_kamar' => $this->input->post('id_kamar',TRUE),
	    );

            $this->Detil_inventori_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('detil_inventori'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Detil_inventori_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('detil_inventori/update_action'),
		'id_detil_inventori' => set_value('id_detil_inventori', $row->id_detil_inventori),
		'id_inventori' => set_value('id_inventori', $row->id_inventori),
		'id_kamar' => set_value('id_kamar', $row->id_kamar),
	    );
            $this->template->load('template','detil_inventori_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('detil_inventori'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_detil_inventori', TRUE));
        } else {
            $data = array(
		'id_detil_inventori' => $this->input->post('id_detil_inventori',TRUE),
		'id_inventori' => $this->input->post('id_inventori',TRUE),
		'id_kamar' => $this->input->post('id_kamar',TRUE),
	    );

            $this->Detil_inventori_model->update($this->input->post('id_detil_inventori', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('detil_inventori'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Detil_inventori_model->get_by_id($id);

        if ($row) {
            $this->Detil_inventori_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('detil_inventori'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('detil_inventori'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('id_detil_inventori', 'id detil inventori', 'trim|required');
	$this->form_validation->set_rules('id_inventori', 'id inventori', 'trim|required');
	$this->form_validation->set_rules('id_kamar', 'id kamar', 'trim|required');

	$this->form_validation->set_rules('id_detil_inventori', 'id_detil_inventori', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Detil_inventori.php */
/* Location: ./application/controllers/Detil_inventori.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-09-23 14:49:15 */
/* http://harviacode.com */