<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Inventori extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        $this->load->model('Inventori_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $inventori = $this->Inventori_model->get_all();

        $data = array(
            'inventori_data' => $inventori
        );

        $this->template->load('template','inventori_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Inventori_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_inventori' => $row->id_inventori,
		'nama_inventori' => $row->nama_inventori,
		'harga_inventori' => $row->harga_inventori,
	    );
            $this->template->load('template','inventori_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('inventori'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('inventori/create_action'),
	    'id_inventori' => set_value('id_inventori'),
	    'nama_inventori' => set_value('nama_inventori'),
	    'harga_inventori' => set_value('harga_inventori'),
	);
        $this->template->load('template','inventori_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'id_inventori' => $this->input->post('id_inventori',TRUE),
		'nama_inventori' => $this->input->post('nama_inventori',TRUE),
		'harga_inventori' => $this->input->post('harga_inventori',TRUE),
	    );

            $this->Inventori_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('inventori'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Inventori_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('inventori/update_action'),
		'id_inventori' => set_value('id_inventori', $row->id_inventori),
		'nama_inventori' => set_value('nama_inventori', $row->nama_inventori),
		'harga_inventori' => set_value('harga_inventori', $row->harga_inventori),
	    );
            $this->template->load('template','inventori_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('inventori'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_inventori', TRUE));
        } else {
            $data = array(
		'id_inventori' => $this->input->post('id_inventori',TRUE),
		'nama_inventori' => $this->input->post('nama_inventori',TRUE),
		'harga_inventori' => $this->input->post('harga_inventori',TRUE),
	    );

            $this->Inventori_model->update($this->input->post('id_inventori', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('inventori'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Inventori_model->get_by_id($id);

        if ($row) {
            $this->Inventori_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('inventori'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('inventori'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('id_inventori', 'id inventori', 'trim|required');
	$this->form_validation->set_rules('nama_inventori', 'nama inventori', 'trim|required');
	$this->form_validation->set_rules('harga_inventori', 'harga inventori', 'trim|required');

	$this->form_validation->set_rules('id_inventori', 'id_inventori', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Inventori.php */
/* Location: ./application/controllers/Inventori.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-09-23 14:48:22 */
/* http://harviacode.com */