<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Status_pemesanan extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        $this->load->model('Status_pemesanan_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $status_pemesanan = $this->Status_pemesanan_model->get_all();

        $data = array(
            'status_pemesanan_data' => $status_pemesanan
        );

        $this->template->load('template','status_pemesanan_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Status_pemesanan_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_status_pemesanan' => $row->id_status_pemesanan,
		'nama_status_pemesanan' => $row->nama_status_pemesanan,
	    );
            $this->template->load('template','status_pemesanan_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('status_pemesanan'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('status_pemesanan/create_action'),
	    'id_status_pemesanan' => set_value('id_status_pemesanan'),
	    'nama_status_pemesanan' => set_value('nama_status_pemesanan'),
	);
        $this->template->load('template','status_pemesanan_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'id_status_pemesanan' => $this->input->post('id_status_pemesanan',TRUE),
		'nama_status_pemesanan' => $this->input->post('nama_status_pemesanan',TRUE),
	    );

            $this->Status_pemesanan_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('status_pemesanan'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Status_pemesanan_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('status_pemesanan/update_action'),
		'id_status_pemesanan' => set_value('id_status_pemesanan', $row->id_status_pemesanan),
		'nama_status_pemesanan' => set_value('nama_status_pemesanan', $row->nama_status_pemesanan),
	    );
            $this->template->load('template','status_pemesanan_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('status_pemesanan'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_status_pemesanan', TRUE));
        } else {
            $data = array(
		'id_status_pemesanan' => $this->input->post('id_status_pemesanan',TRUE),
		'nama_status_pemesanan' => $this->input->post('nama_status_pemesanan',TRUE),
	    );

            $this->Status_pemesanan_model->update($this->input->post('id_status_pemesanan', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('status_pemesanan'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Status_pemesanan_model->get_by_id($id);

        if ($row) {
            $this->Status_pemesanan_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('status_pemesanan'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('status_pemesanan'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('id_status_pemesanan', 'id status pemesanan', 'trim|required');
	$this->form_validation->set_rules('nama_status_pemesanan', 'nama status pemesanan', 'trim|required');

	$this->form_validation->set_rules('id_status_pemesanan', 'id_status_pemesanan', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Status_pemesanan.php */
/* Location: ./application/controllers/Status_pemesanan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-09-23 16:03:03 */
/* http://harviacode.com */