<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Check_in_model extends CI_Model
{

    public $table = 'check_in';
    public $id = 'id_ci';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function update_ci()
    {
        $data = array(
            'real_ci' => $this->input->post('real_ci'),
            'charge_ci' => $this->input->post('charge_ci')
        );
        $where = array(
            'id_pemesanan' => $this->input->post('id_pemesanan')
            );
        $this->db->where($where);
        $this->db->update('check_in', $data);
    }
    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_booking($id){
        $query = $this->db->query("select concat(nama_depan_tamu,' ',nama_belakang_tamu) as tamu, concat(jumlah_dewasa,' Dewasa ',jumlah_anak,' Anak') as jumlah_tamu, concat(nama_kamar,' - ',no_kamar) as kamar, plan_ci, if(now() < plan_ci, (presentase_eci * total_harga / 100), 0) as charge_ci
            from check_in ci join pemesanan p on p.id_pemesanan = ci.id_pemesanan join tamu t on t.id_tamu = p.id_tamu join kamar k on k.id_kamar = p.id_kamar join ketentuan_waktu kw on kw.id_kw = ci.id_kw
            where p.id_pemesanan = '$id' ");
        return $query->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_ci', $q);
	$this->db->or_like('id_ci', $q);
	$this->db->or_like('id_kw', $q);
	$this->db->or_like('plan_ci', $q);
	$this->db->or_like('real_ci', $q);
	$this->db->or_like('charge_ci', $q);
	$this->db->or_like('id_pemesanan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_ci', $q);
	$this->db->or_like('id_ci', $q);
	$this->db->or_like('id_kw', $q);
	$this->db->or_like('plan_ci', $q);
	$this->db->or_like('real_ci', $q);
	$this->db->or_like('charge_ci', $q);
	$this->db->or_like('id_pemesanan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Check_in_model.php */
/* Location: ./application/models/Check_in_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-11-01 04:11:28 */
/* http://harviacode.com */