<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pemesanan_model extends CI_Model
{

    public $table = 'pemesanan';
    public $id = 'id_pemesanan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function get_kamar(){
        $this->db->query("select concat('no_kamar','-','nama_kamar') as kamar from kamar where status")
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_pemesanan', $q);
	$this->db->or_like('id_pemesanan', $q);
	$this->db->or_like('waktu_pemesanan', $q);
	$this->db->or_like('uang_muka', $q);
	$this->db->or_like('sisa_bayar', $q);
	$this->db->or_like('total_harga', $q);
	$this->db->or_like('id_channel', $q);
	$this->db->or_like('id_promo', $q);
	$this->db->or_like('id_kamar', $q);
	$this->db->or_like('id_tamu', $q);
	$this->db->or_like('jumlah_dewasa', $q);
	$this->db->or_like('jumlah_anak', $q);
	$this->db->or_like('umur_anak', $q);
	$this->db->or_like('permintaan_spesial', $q);
	$this->db->or_like('batas_waktu_pemesanan', $q);
	$this->db->or_like('id_status_pemesanan', $q);
	$this->db->or_like('id_pegawai', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_pemesanan', $q);
	$this->db->or_like('id_pemesanan', $q);
	$this->db->or_like('waktu_pemesanan', $q);
	$this->db->or_like('uang_muka', $q);
	$this->db->or_like('sisa_bayar', $q);
	$this->db->or_like('total_harga', $q);
	$this->db->or_like('id_channel', $q);
	$this->db->or_like('id_promo', $q);
	$this->db->or_like('id_kamar', $q);
	$this->db->or_like('id_tamu', $q);
	$this->db->or_like('jumlah_dewasa', $q);
	$this->db->or_like('jumlah_anak', $q);
	$this->db->or_like('umur_anak', $q);
	$this->db->or_like('permintaan_spesial', $q);
	$this->db->or_like('batas_waktu_pemesanan', $q);
	$this->db->or_like('id_status_pemesanan', $q);
	$this->db->or_like('id_pegawai', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pemesanan_model.php */
/* Location: ./application/models/Pemesanan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-09-27 08:26:53 */
/* http://harviacode.com */